<?xml version="1.0" encoding="utf-8"?><Database Name="FerreteriaPA" Class="ConexionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CASA;Initial Catalog=FerreteriaPA;Integrated Security=True;Encrypt=False" SettingsObjectName="CapaDatos.Properties.Settings" SettingsPropertyName="FerreteriaPAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CategoriaProducto" Member="CategoriaProducto">
    <Type Name="CategoriaProducto">
      <Column Name="Id_CategoriaProducto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="CategoriaProducto_Producto" Member="Producto" ThisKey="Id_CategoriaProducto" OtherKey="Id_CategoriaProducto" Type="Producto" />
    </Type>
  </Table>
  <Table Name="dbo.Cliente" Member="Cliente">
    <Type Name="Cliente">
      <Column Name="Id_Cliente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Cuenta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Edad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Cliente_Factura" Member="Factura" ThisKey="Id_Cliente" OtherKey="Id_Cliente" Type="Factura" />
      <Association Name="Cuenta_Cliente" Member="Cuenta" ThisKey="Id_Cuenta" OtherKey="Id_Cuenta" Type="Cuenta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cuenta" Member="Cuenta">
    <Type Name="Cuenta">
      <Column Name="Id_Cuenta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_rol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Cuenta_Cliente" Member="Cliente" ThisKey="Id_Cuenta" OtherKey="Id_Cuenta" Type="Cliente" />
      <Association Name="Rol_Cuenta" Member="Rol" ThisKey="Id_rol" OtherKey="Id_rol" Type="Rol" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DetalleFactura" Member="DetalleFactura">
    <Type Name="DetalleFactura">
      <Column Name="Id_DetalleFactura" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Factura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Association Name="Factura_DetalleFactura" Member="Factura" ThisKey="Id_Factura" OtherKey="Id_Factura" Type="Factura" IsForeignKey="true" />
      <Association Name="Producto_DetalleFactura" Member="Producto" ThisKey="Id_Producto" OtherKey="Id_Producto" Type="Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Empresa" Member="Empresa">
    <Type Name="Empresa">
      <Column Name="Id_Empresa" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ruc" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Representante" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Observacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Empresa_Proveedor" Member="Proveedor" ThisKey="Id_Empresa" OtherKey="Id_Empresa" Type="Proveedor" />
    </Type>
  </Table>
  <Table Name="dbo.EntradaProducto" Member="EntradaProducto">
    <Type Name="EntradaProducto">
      <Column Name="Id_EntradaProducto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Proveedor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaIngreso" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CostoUnitario" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="CostoTotal" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Observacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Proveedor_EntradaProducto" Member="Proveedor" ThisKey="Id_Proveedor" OtherKey="Id_Proveedor" Type="Proveedor" IsForeignKey="true" />
      <Association Name="Producto_EntradaProducto" Member="Producto" ThisKey="Id_Producto" OtherKey="Id_Producto" Type="Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Factura" Member="Factura">
    <Type Name="Factura">
      <Column Name="Id_Factura" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Cliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaEmision" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="MetodoPago" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Iva" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Factura_DetalleFactura" Member="DetalleFactura" ThisKey="Id_Factura" OtherKey="Id_Factura" Type="DetalleFactura" />
      <Association Name="Cliente_Factura" Member="Cliente" ThisKey="Id_Cliente" OtherKey="Id_Cliente" Type="Cliente" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Proveedor" Member="Proveedor">
    <Type Name="Proveedor">
      <Column Name="Id_Proveedor" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Empresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Edad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Observacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Proveedor_EntradaProducto" Member="EntradaProducto" ThisKey="Id_Proveedor" OtherKey="Id_Proveedor" Type="EntradaProducto" />
      <Association Name="Empresa_Proveedor" Member="Empresa" ThisKey="Id_Empresa" OtherKey="Id_Empresa" Type="Empresa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Producto" Member="Producto">
    <Type Name="Producto">
      <Column Name="Id_Producto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_CategoriaProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Stock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Icono" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Producto_DetalleFactura" Member="DetalleFactura" ThisKey="Id_Producto" OtherKey="Id_Producto" Type="DetalleFactura" />
      <Association Name="Producto_EntradaProducto" Member="EntradaProducto" ThisKey="Id_Producto" OtherKey="Id_Producto" Type="EntradaProducto" />
      <Association Name="Producto_SalidaProducto" Member="SalidaProducto" ThisKey="Id_Producto" OtherKey="Id_Producto" Type="SalidaProducto" />
      <Association Name="CategoriaProducto_Producto" Member="CategoriaProducto" ThisKey="Id_CategoriaProducto" OtherKey="Id_CategoriaProducto" Type="CategoriaProducto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rol" Member="Rol">
    <Type Name="Rol">
      <Column Name="Id_rol" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Rol_Cuenta" Member="Cuenta" ThisKey="Id_rol" OtherKey="Id_rol" Type="Cuenta" />
    </Type>
  </Table>
  <Table Name="dbo.SalidaProducto" Member="SalidaProducto">
    <Type Name="SalidaProducto">
      <Column Name="Id_SalidaProducto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaSalida" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Motivo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Observacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Producto_SalidaProducto" Member="Producto" ThisKey="Id_Producto" OtherKey="Id_Producto" Type="Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.CP_EliminarCategoriaProducto" Method="CP_EliminarCategoriaProducto">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_EliminarCliente" Method="CP_EliminarCliente">
    <Parameter Name="Id_Cliente" Parameter="id_Cliente" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_EliminarCuenta" Method="CP_EliminarCuenta">
    <Parameter Name="idCuenta" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_EliminarEmpresa" Method="CP_EliminarEmpresa">
    <Parameter Name="idEmpresa" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_EliminarEntradaProducto" Method="CP_EliminarEntradaProducto">
    <Parameter Name="idEntrada" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_EliminarDetalleFactura" Method="CP_EliminarDetalleFactura">
    <Parameter Name="idDetalleFactura" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_EliminarFactura" Method="CP_EliminarFactura">
    <Parameter Name="idFactura" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_EliminarProducto" Method="CP_EliminarProducto">
    <Parameter Name="Id_Producto" Parameter="id_Producto" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_EliminarProveedor" Method="CP_EliminarProveedor">
    <Parameter Name="Id_Prove" Parameter="id_Prove" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_EliminarRol" Method="CP_EliminarRol">
    <Parameter Name="idRol" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_EliminarSalidaProducto" Method="CP_EliminarSalidaProducto">
    <Parameter Name="idSalida" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_FiltraEmpresas" Method="CP_FiltraEmpresas">
    <Parameter Name="valor" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="CP_FiltraEmpresasResult">
      <Column Name="Id_Empresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ruc" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Representante" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Observacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CP_FiltraEntradasProductos" Method="CP_FiltraEntradasProductos">
    <Parameter Name="valor" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="CP_FiltraEntradasProductosResult">
      <Column Name="Id_EntradaProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Proveedor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaIngreso" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CostoUnitario" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="CostoTotal" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Observacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CP_FiltrarCategoriasProductos" Method="CP_FiltrarCategoriasProductos">
    <Parameter Name="Valor" Parameter="valor" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="CP_FiltrarCategoriasProductosResult">
      <Column Name="Id_CategoriaProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CP_FiltrarClientes" Method="CP_FiltrarClientes">
    <Parameter Name="Valor" Parameter="valor" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="CP_FiltrarClientesResult">
      <Column Name="Id_Cliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Cuenta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Edad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CP_FiltrarCuentas" Method="CP_FiltrarCuentas">
    <Parameter Name="mail" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="passwd" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="CP_FiltrarCuentasResult">
      <Column Name="Id_Cuenta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_rol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CP_FiltrarDetallesFacturas" Method="CP_FiltrarDetallesFacturas">
    <Parameter Name="Valor" Parameter="valor" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="CP_FiltrarDetallesFacturasResult">
      <Column Name="Id_DetalleFactura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Factura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CP_FiltrarFacturas" Method="CP_FiltrarFacturas">
    <Parameter Name="Valor" Parameter="valor" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="CP_FiltrarFacturasResult">
      <Column Name="Id_Factura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Cliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaEmision" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="MetodoPago" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Iva" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CP_FiltrarProductos" Method="CP_FiltrarProductos">
    <Parameter Name="Valor" Parameter="valor" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="CP_FiltrarProductosResult">
      <Column Name="Id_Producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_CategoriaProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Stock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Icono" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CP_FiltrarProveedores" Method="CP_FiltrarProveedores">
    <Parameter Name="Valor" Parameter="valor" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="CP_FiltrarProveedoresResult">
      <Column Name="Id_Proveedor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Empresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Edad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Observacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CP_FiltrarRoles" Method="CP_FiltrarRoles">
    <Parameter Name="valor" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="CP_FiltrarRolesResult">
      <Column Name="Id_rol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CP_FiltraSalidasProductos" Method="CP_FiltraSalidasProductos">
    <Parameter Name="valor" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="CP_FiltraSalidasProductosResult">
      <Column Name="Id_SalidaProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaSalida" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Motivo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Observacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CP_InsertarCategoriaProducto" Method="CP_InsertarCategoriaProducto">
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="descripcion" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_InsertarCliente" Method="CP_InsertarCliente">
    <Parameter Name="idCuenta" Type="System.Int32" DbType="Int" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="fechaNaci" Type="System.DateTime" DbType="Date" />
    <Parameter Name="edad" Type="System.Int32" DbType="Int" />
    <Parameter Name="telefono" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_InsertarCuenta" Method="CP_InsertarCuenta">
    <Parameter Name="idRol" Type="System.Int32" DbType="Int" />
    <Parameter Name="mail" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_InsertarDetalleFactura" Method="CP_InsertarDetalleFactura">
    <Parameter Name="idProducto" Type="System.Int32" DbType="Int" />
    <Parameter Name="idFactura" Type="System.Int32" DbType="Int" />
    <Parameter Name="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="subtotal" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_InsertarEmpresa" Method="CP_InsertarEmpresa">
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ruc" Type="System.String" DbType="VarChar(9)" />
    <Parameter Name="direccion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="representante" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="telefono" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="mail" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="observacion" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_InsertarEntradaProducto" Method="CP_InsertarEntradaProducto">
    <Parameter Name="idProducto" Type="System.Int32" DbType="Int" />
    <Parameter Name="idProveedor" Type="System.Int32" DbType="Int" />
    <Parameter Name="fechaIngreso" Type="System.DateTime" DbType="Date" />
    <Parameter Name="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="costoUnitario" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="costoTotal" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="observacion" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_InsertarFactura" Method="CP_InsertarFactura">
    <Parameter Name="idCliente" Type="System.Int32" DbType="Int" />
    <Parameter Name="fechaEmision" Type="System.DateTime" DbType="Date" />
    <Parameter Name="metodoPago" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="total" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="iva" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_InsertarProducto" Method="CP_InsertarProducto">
    <Parameter Name="Id_CategoriaProducto" Parameter="id_CategoriaProducto" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Precio" Parameter="precio" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Stock" Parameter="stock" Type="System.Int32" DbType="Int" />
    <Parameter Name="Estado" Parameter="estado" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Icono" Parameter="icono" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_InsertarProveedor" Method="CP_InsertarProveedor">
    <Parameter Name="Id_Empresa" Parameter="id_Empresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="fechaNaci" Type="System.DateTime" DbType="Date" />
    <Parameter Name="edad" Type="System.Int32" DbType="Int" />
    <Parameter Name="mail" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="telefono" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="observacion" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_InsertarRol" Method="CP_InsertarRol">
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_InsertarSalidaProducto" Method="CP_InsertarSalidaProducto">
    <Parameter Name="idProducto" Type="System.Int32" DbType="Int" />
    <Parameter Name="fechaSalida" Type="System.DateTime" DbType="Date" />
    <Parameter Name="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="motivo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="observacion" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_ListarCategoriasProductos" Method="CP_ListarCategoriasProductos">
    <ElementType Name="CP_ListarCategoriasProductosResult">
      <Column Name="Id_CategoriaProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CP_ListarClientes" Method="CP_ListarClientes">
    <ElementType Name="CP_ListarClientesResult">
      <Column Name="Id_Cliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Cuenta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Edad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CP_ListarCuentas" Method="CP_ListarCuentas">
    <ElementType Name="CP_ListarCuentasResult">
      <Column Name="Id_Cuenta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_rol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CP_ListarDetalleFacturas" Method="CP_ListarDetalleFacturas">
    <ElementType Name="CP_ListarDetalleFacturasResult">
      <Column Name="Id_DetalleFactura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Factura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CP_ListarEmpresas" Method="CP_ListarEmpresas">
    <ElementType Name="CP_ListarEmpresasResult">
      <Column Name="Id_Empresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ruc" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Representante" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Observacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CP_ListarEntradaProductos" Method="CP_ListarEntradaProductos">
    <ElementType Name="CP_ListarEntradaProductosResult">
      <Column Name="Id_EntradaProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Proveedor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaIngreso" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CostoUnitario" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="CostoTotal" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Observacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CP_ListarProveedores" Method="CP_ListarProveedores">
    <ElementType Name="CP_ListarProveedoresResult">
      <Column Name="Id_Proveedor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Empresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Edad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Observacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CP_ListarRoles" Method="CP_ListarRoles">
    <ElementType Name="CP_ListarRolesResult">
      <Column Name="Id_rol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CP_ListarSalidaProductos" Method="CP_ListarSalidaProductos">
    <ElementType Name="CP_ListarSalidaProductosResult">
      <Column Name="Id_SalidaProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaSalida" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Motivo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Observacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CP_ModificarCliente" Method="CP_ModificarCliente">
    <Parameter Name="Id_Cliente" Parameter="id_Cliente" Type="System.Int32" DbType="Int" />
    <Parameter Name="Id_Cuenta" Parameter="id_Cuenta" Type="System.Int32" DbType="Int" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="fechaNaci" Type="System.DateTime" DbType="Date" />
    <Parameter Name="edad" Type="System.Int32" DbType="Int" />
    <Parameter Name="telefono" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_ModificarCuenta" Method="CP_ModificarCuenta">
    <Parameter Name="id_cuenta" Type="System.Int32" DbType="Int" />
    <Parameter Name="id_rol" Type="System.Int32" DbType="Int" />
    <Parameter Name="mail" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_ModificarDetalleFactura" Method="CP_ModificarDetalleFactura">
    <Parameter Name="Id_DetalleFactura" Parameter="id_DetalleFactura" Type="System.Int32" DbType="Int" />
    <Parameter Name="Id_Producto" Parameter="id_Producto" Type="System.Int32" DbType="Int" />
    <Parameter Name="Id_Factura" Parameter="id_Factura" Type="System.Int32" DbType="Int" />
    <Parameter Name="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="subtotal" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_ModificarCategoriaProducto" Method="CP_ModificarCategoriaProducto">
    <Parameter Name="id_categoria" Type="System.Int32" DbType="Int" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="descripcion" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_ListarFacturas" Method="CP_ListarFacturas">
    <ElementType Name="CP_ListarFacturasResult">
      <Column Name="Id_Factura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Cliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaEmision" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="MetodoPago" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Iva" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CP_ListarProductos" Method="CP_ListarProductos">
    <ElementType Name="CP_ListarProductosResult">
      <Column Name="Id_Producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_CategoriaProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Stock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Icono" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CP_ModificarEmpresa" Method="CP_ModificarEmpresa">
    <Parameter Name="Id_Empresa" Parameter="id_Empresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ruc" Type="System.String" DbType="VarChar(9)" />
    <Parameter Name="direccion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="representante" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="telefono" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="mail" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="observacion" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_ModificarEntradaProducto" Method="CP_ModificarEntradaProducto">
    <Parameter Name="Id_EntradaProducto" Parameter="id_EntradaProducto" Type="System.Int32" DbType="Int" />
    <Parameter Name="Id_Producto" Parameter="id_Producto" Type="System.Int32" DbType="Int" />
    <Parameter Name="Id_Proveedor" Parameter="id_Proveedor" Type="System.Int32" DbType="Int" />
    <Parameter Name="fechaIngreso" Type="System.DateTime" DbType="Date" />
    <Parameter Name="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="costoUnitario" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="costoTotal" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="observacion" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_ModificarFactura" Method="CP_ModificarFactura">
    <Parameter Name="Id_factura" Parameter="id_factura" Type="System.Int32" DbType="Int" />
    <Parameter Name="Id_Cliente" Parameter="id_Cliente" Type="System.Int32" DbType="Int" />
    <Parameter Name="fechaEmision" Type="System.DateTime" DbType="Date" />
    <Parameter Name="metodoPago" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="total" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="iva" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_ModificarProducto" Method="CP_ModificarProducto">
    <Parameter Name="Id_Producto" Parameter="id_Producto" Type="System.Int32" DbType="Int" />
    <Parameter Name="Id_Categoria" Parameter="id_Categoria" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Precio" Parameter="precio" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Stock" Parameter="stock" Type="System.Int32" DbType="Int" />
    <Parameter Name="estado" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="icono" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_ModificarProveedor" Method="CP_ModificarProveedor">
    <Parameter Name="Id_Proveedor" Parameter="id_Proveedor" Type="System.Int32" DbType="Int" />
    <Parameter Name="Id_Empresa" Parameter="id_Empresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="fechaNaci" Type="System.DateTime" DbType="Date" />
    <Parameter Name="edad" Type="System.Int32" DbType="Int" />
    <Parameter Name="mail" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="telefono" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="observacion" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_ModificarRol" Method="CP_ModificarRol">
    <Parameter Name="id_rol" Type="System.Int32" DbType="Int" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CP_ModificarSalidaProducto" Method="CP_ModificarSalidaProducto">
    <Parameter Name="Id_SalidaProducto" Parameter="id_SalidaProducto" Type="System.Int32" DbType="Int" />
    <Parameter Name="Id_Producto" Parameter="id_Producto" Type="System.Int32" DbType="Int" />
    <Parameter Name="fechaSalida" Type="System.DateTime" DbType="Date" />
    <Parameter Name="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="motivo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="observacion" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FiltrarVistaClienteCuentaMail" Method="FiltrarVistaClienteCuentaMail">
    <Parameter Name="clave" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="FiltrarVistaClienteCuentaMailResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Edad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.FiltrarVistaCuentaRol" Method="FiltrarVistaCuentaRol">
    <Parameter Name="clave" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="FiltrarVistaCuentaRolResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rol" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.FiltrarVistaDetalleFactura" Method="FiltrarVistaDetalleFactura">
    <Parameter Name="clave" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="FiltrarVistaDetalleFacturaResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Producto" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.FiltrarVistaEntradaProudcto" Method="FiltrarVistaEntradaProudcto">
    <Parameter Name="clave" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="FiltrarVistaEntradaProudctoResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Producto" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Proveedor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailProv" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Empresa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailEmp" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaIngreso" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[C/U]" Member="C_U" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Observacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.FiltrarVistaFacturaCliente" Method="FiltrarVistaFacturaCliente">
    <Parameter Name="clave" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="FiltrarVistaFacturaClienteResult">
      <Column Name="[Num-Factura]" Member="Num_Factura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cliente" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaEmision" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="MetodoPago" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[%IVA]" Member="_IVA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[$Total]" Member="_Total" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.FiltrarVistaProductoCategoria" Method="FiltrarVistaProductoCategoria">
    <Parameter Name="clave" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="FiltrarVistaProductoCategoriaResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Producto" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Stock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Icono" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.FiltrarVistaProveedorEmpresa" Method="FiltrarVistaProveedorEmpresa">
    <Parameter Name="clave" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="FiltrarVistaProveedorEmpresaResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Empresa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Proveedor" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Edad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Observacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.FiltrarVistaSalidaProudcto" Method="FiltrarVistaSalidaProudcto">
    <Parameter Name="clave" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="FiltrarVistaSalidaProudctoResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Producto" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaSalida" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Motivo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Observacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>